:sparkles: add graphite support
yazgoo/kafka-lag-exporter pull request #1
Opened 2019-12-11 15:37 UTC by yazgoo

2019-12-11 17:06 UTC, yazgoo commented
new conf to enable graphite
```conf
kafka-lag-exporter {
  graphite-cluster-host = "localhost"
  graphite-cluster-port = 2003
```

2019-12-12 10:08 UTC, cheleb requested changes

2019-12-12 10:08 UTC, OlivierNouguier commented on src/main/scala/com/lightbend/kafkalagexporter/PrometheusEndpointSink.scala
> +    new Graphite(cluster.host, cluster.port).start(registry, 20)
Magic number

2019-12-12 10:08 UTC, OlivierNouguier commented on src/main/scala/com/lightbend/kafkalagexporter/PrometheusEndpointSink.scala
> +  graphiteCluster.map { cluster =>
prefer foreach if side effect only
btw, maybe Graphite should be stopped

2019-12-16 09:55 UTC, cheleb approved these changes

2020-01-22 10:02 UTC, merged